/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#353435',
        'on-secondary-fixed-variant': '#43474b',
        'on-primary': '#2f3133',
        'on-secondary-fixed': '#181c20',
        'on-tertiary-fixed': '#201b17',
        'primary-fixed-dim': '#c6c6c9',
        'on-primary-fixed': '#1a1c1e',
        'on-tertiary': '#352f2b',
        'tertiary-fixed-dim': '#cfc5be',
        'tertiary-container': '#201b17',
        'surface': '#141313',
        'surface-dim': '#141313',
        'on-tertiary-fixed-variant': '#4c4641',
        'secondary-fixed': '#e0e3e8',
        'on-secondary': '#2d3135',
        'inverse-surface': '#e5e2e1',
        'on-primary-container': '#838486',
        'error-container': '#93000a',
        'error': '#ffb4ab',
        'surface-bright': '#3a3939',
        'surface-tint': '#c6c6c9',
        'on-surface-variant': '#c5c6ca',
        'on-error': '#690005',
        'surface-container': '#201f1f',
        'on-tertiary-container': '#8b837d',
        'secondary-container': '#484c50',
        'secondary-fixed-dim': '#c3c7cc',
        'tertiary-fixed': '#ebe0da',
        'on-primary-fixed-variant': '#454749',
        'primary-container': '#1a1c1e',
        'primary-fixed': '#e2e2e5',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-container': '#b9bcc1',
        'inverse-primary': '#5d5e61',
        'inverse-on-surface': '#313030',
        'on-error-container': '#ffdad6',
        'tertiary': '#cfc5be',
        'outline-variant': '#44474a',
        'surface-container-highest': '#353435',
        'surface-container-low': '#1c1b1b',
        'background': '#141313',
        'on-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'secondary': '#c3c7cc',
        'outline': '#8f9194',
        'surface-container-high': '#2a2a2a',
        'primary': '#c6c6c9',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '16px',
        'container-margin': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'unit': '4px',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      }
    },
  },
  plugins: [],
};
