/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#002b80",
        "on-secondary": "#283500",
        "on-secondary-container": "#556d00",
        "error-container": "#93000a",
        "surface-container-lowest": "#000c2d",
        "on-primary-fixed": "#00174d",
        "tertiary": "#c6c6c7",
        "on-error": "#690005",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#214195",
        "on-surface-variant": "#c4c6d3",
        "surface-bright": "#22376a",
        "surface-container": "#021c4f",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-primary": "#00297a",
        "surface-tint": "#b5c4ff",
        "error": "#ffb4ab",
        "tertiary-container": "#313333",
        "on-background": "#dae2ff",
        "secondary": "#ffffff",
        "on-secondary-fixed": "#161e00",
        "on-tertiary": "#2f3131",
        "outline": "#8e909d",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-highest": "#1d3265",
        "surface-container-high": "#10275a",
        "on-primary-container": "#7c97f0",
        "primary": "#b5c4ff",
        "on-tertiary-container": "#9a9b9b",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-low": "#001848",
        "surface": "#001037",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#abd600",
        "outline-variant": "#444652",
        "inverse-primary": "#3d59ae",
        "on-secondary-fixed-variant": "#3c4d00",
        "secondary-fixed": "#c3f400",
        "tertiary-fixed": "#e2e2e2",
        "background": "#001037",
        "surface-variant": "#1d3265",
        "secondary-container": "#c3f400",
        "surface-dim": "#001037",
        "on-surface": "#dae2ff",
        "inverse-surface": "#dae2ff",
        "inverse-on-surface": "#182e60",
        "primary-fixed-dim": "#b5c4ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "64px",
        "gutter": "20px",
        "lg": "40px",
        "base": "4px",
        "margin-desktop": "48px",
        "md": "24px",
        "xs": "8px",
        "sm": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-lg": ["Archivo Narrow", "sans-serif"],
        "display-lg": ["Archivo Narrow", "sans-serif"],
        "body-md": ["Archivo Narrow", "sans-serif"],
        "label-caps": ["Archivo Narrow", "sans-serif"],
        "body-lg": ["Archivo Narrow", "sans-serif"],
        "headline-sm": ["Archivo Narrow", "sans-serif"],
        "display-lg-mobile": ["Archivo Narrow", "sans-serif"],
        "stats-xl": ["Archivo Narrow", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["72px", { "lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "display-lg-mobile": ["48px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "stats-xl": ["40px", { "lineHeight": "40px", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
